"""
AegisOps — Tool: Incident Report Generator

Generates a structured incident report after the agent completes
remediation actions. The report contains:
  • What was detected (drift event details)
  • What actions were taken
  • Which GCP resources were affected
  • Confidence score and resolution status

Reports are output as both JSON and human-readable text,
satisfying the website requirement: "Structured incident report
per agent run" with "JSON + natural language".
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone

from pydantic import BaseModel, Field

from .retry import with_retry


# ---------------------------------------------------------------------------
# Output Schema
# ---------------------------------------------------------------------------

class IncidentReport(BaseModel):
    """Structured incident report generated by the agent."""

    incident_id: str
    timestamp: str
    model_id: str
    severity: str
    detection_summary: str
    actions_taken: list[str]
    affected_resources: list[str]
    confidence_score: float
    resolution_status: str
    human_summary: str


# ---------------------------------------------------------------------------
# Tool Implementation
# ---------------------------------------------------------------------------

@with_retry(max_attempts=2)
def generate_incident_report(
    detection_summary: str,
    severity: str,
    actions_taken: str,
    affected_resources: str,
    confidence_score: float = 0.95,
    resolution_status: str = "resolved",
    model_id: str = "unknown",
) -> dict:
    """
    Generate and save a structured incident report after remediation.

    The agent calls this tool as the final step in every remediation
    workflow. It produces both a JSON record and a human-readable
    summary for the incident log.

    Args:
        detection_summary: What was detected (e.g., "PSI drift on
            income_bracket feature, PSI=0.38 vs baseline 0.05").
        severity: Drift severity — "low", "moderate", or "critical".
        actions_taken: Comma-separated list of actions taken (e.g.,
            "isolate_data_batch, trigger_retraining_pipeline").
        affected_resources: Comma-separated list of GCP resources
            affected (e.g., "gs://bucket/batch-123, vertex-pipeline-456").
        confidence_score: Agent's confidence in its diagnosis (0.0–1.0).
        resolution_status: Current status — "resolved", "in_progress",
            "requires_review".
        model_id: Vertex AI model resource name.

    Returns:
        dict: The full incident report with JSON and human summary.
    """
    # Generate unique incident ID and timestamp
    incident_id = f"INC-{datetime.now(timezone.utc).strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
    timestamp = datetime.now(timezone.utc).isoformat()

    # Parse comma-separated strings into lists
    actions_list = [a.strip() for a in actions_taken.split(",") if a.strip()]
    resources_list = [r.strip() for r in affected_resources.split(",") if r.strip()]

    # Build human-readable summary
    severity_emoji = {"low": "[LOW]", "moderate": "[MOD]", "critical": "[CRIT]"}.get(severity, "[INFO]")
    status_emoji = {"resolved": "[DONE]", "in_progress": "[WIP]", "requires_review": "[WARN]"}.get(resolution_status, "[?]")

    human_summary = (
        f"{'━' * 60}\n"
        f"  INCIDENT REPORT — {incident_id}\n"
        f"{'━' * 60}\n"
        f"\n"
        f"  {severity_emoji} Severity:    {severity.upper()}\n"
        f"   Timestamp:   {timestamp}\n"
        f"   Model:       {model_id}\n"
        f"   Confidence:  {confidence_score:.0%}\n"
        f"  {status_emoji} Status:      {resolution_status}\n"
        f"\n"
        f"   Detection:\n"
        f"     {detection_summary}\n"
        f"\n"
        f"   Actions Taken:\n"
    )
    for i, action in enumerate(actions_list, 1):
        human_summary += f"     {i}. {action}\n"

    human_summary += f"\n   Affected Resources:\n"
    for resource in resources_list:
        human_summary += f"     • {resource}\n"

    human_summary += f"\n{'━' * 60}"

    # Build the report object
    report = IncidentReport(
        incident_id=incident_id,
        timestamp=timestamp,
        model_id=model_id,
        severity=severity,
        detection_summary=detection_summary,
        actions_taken=actions_list,
        affected_resources=resources_list,
        confidence_score=confidence_score,
        resolution_status=resolution_status,
        human_summary=human_summary,
    )

    # Save to incidents directory
    incidents_dir = os.path.join(os.path.dirname(__file__), "..", "..", "incidents")
    os.makedirs(incidents_dir, exist_ok=True)
    report_path = os.path.join(incidents_dir, f"{incident_id}.json")

    with open(report_path, "w") as f:
        json.dump(report.model_dump(), f, indent=2)

    # Print the human-readable summary
    print(f"\n{human_summary}\n")
    print(f"   Report saved: {report_path}\n")

    return report.model_dump()
